module ncurses_const
    !! Auto-generated ncurses parameters. Do not modify.
    use, intrinsic :: iso_c_binding
    implicit none (type, external)
    public

    integer(c_long), parameter :: ACS_BLOCK    = int(z'400030', c_long)
    integer(c_long), parameter :: ACS_BOARD    = int(z'400068', c_long)
    integer(c_long), parameter :: ACS_BTEE     = int(z'400076', c_long)
    integer(c_long), parameter :: ACS_BULLET   = int(z'40007e', c_long)
    integer(c_long), parameter :: ACS_CKBOARD  = int(z'400061', c_long)
    integer(c_long), parameter :: ACS_DARROW   = int(z'40002e', c_long)
    integer(c_long), parameter :: ACS_DEGREE   = int(z'400066', c_long)
    integer(c_long), parameter :: ACS_DIAMOND  = int(z'400060', c_long)
    integer(c_long), parameter :: ACS_GEQUAL   = int(z'40007a', c_long)
    integer(c_long), parameter :: ACS_HLINE    = int(z'400071', c_long)
    integer(c_long), parameter :: ACS_LANTERN  = int(z'400069', c_long)
    integer(c_long), parameter :: ACS_LARROW   = int(z'40002c', c_long)
    integer(c_long), parameter :: ACS_LEQUAL   = int(z'400079', c_long)
    integer(c_long), parameter :: ACS_LLCORNER = int(z'40006d', c_long)
    integer(c_long), parameter :: ACS_LRCORNER = int(z'40006a', c_long)
    integer(c_long), parameter :: ACS_LTEE     = int(z'400074', c_long)
    integer(c_long), parameter :: ACS_NEQUAL   = int(z'40007c', c_long)
    integer(c_long), parameter :: ACS_PI       = int(z'40007b', c_long)
    integer(c_long), parameter :: ACS_PLMINUS  = int(z'400067', c_long)
    integer(c_long), parameter :: ACS_PLUS     = int(z'40006e', c_long)
    integer(c_long), parameter :: ACS_RARROW   = int(z'40002b', c_long)
    integer(c_long), parameter :: ACS_RTEE     = int(z'400075', c_long)
    integer(c_long), parameter :: ACS_S1       = int(z'40006f', c_long)
    integer(c_long), parameter :: ACS_S3       = int(z'400070', c_long)
    integer(c_long), parameter :: ACS_S7       = int(z'400072', c_long)
    integer(c_long), parameter :: ACS_S9       = int(z'400073', c_long)
    integer(c_long), parameter :: ACS_STERLING = int(z'40007d', c_long)
    integer(c_long), parameter :: ACS_TTEE     = int(z'400077', c_long)
    integer(c_long), parameter :: ACS_UARROW   = int(z'40002d', c_long)
    integer(c_long), parameter :: ACS_ULCORNER = int(z'40006c', c_long)
    integer(c_long), parameter :: ACS_URCORNER = int(z'40006b', c_long)
    integer(c_long), parameter :: ACS_VLINE    = int(z'400078', c_long)

    integer(c_int), parameter :: A_NORMAL     = int(z'00000000')
    integer(c_int), parameter :: A_ATTRIBUTES = int(z'ffffff00')
    integer(c_int), parameter :: A_CHARTEXT   = int(z'000000ff')
    integer(c_int), parameter :: A_COLOR      = int(z'0000ff00')
    integer(c_int), parameter :: A_STANDOUT   = int(z'00010000')
    integer(c_int), parameter :: A_UNDERLINE  = int(z'00020000')
    integer(c_int), parameter :: A_REVERSE    = int(z'00040000')
    integer(c_int), parameter :: A_BLINK      = int(z'00080000')
    integer(c_int), parameter :: A_DIM        = int(z'00100000')
    integer(c_int), parameter :: A_BOLD       = int(z'00200000')
    integer(c_int), parameter :: A_ALTCHARSET = int(z'00400000')
    integer(c_int), parameter :: A_INVIS      = int(z'00800000')
    integer(c_int), parameter :: A_PROTECT    = int(z'01000000')

    integer(c_short), parameter :: COLOR_BLACK   = 0_c_short
    integer(c_short), parameter :: COLOR_RED     = 1_c_short
    integer(c_short), parameter :: COLOR_GREEN   = 2_c_short
    integer(c_short), parameter :: COLOR_YELLOW  = 3_c_short
    integer(c_short), parameter :: COLOR_BLUE    = 4_c_short
    integer(c_short), parameter :: COLOR_MAGENTA = 5_c_short
    integer(c_short), parameter :: COLOR_CYAN    = 6_c_short
    integer(c_short), parameter :: COLOR_WHITE   = 7_c_short

    integer(c_int), parameter :: KEY_CODE_YES  = int(o'400')
    integer(c_int), parameter :: KEY_MIN       = int(o'401')
    integer(c_int), parameter :: KEY_BREAK     = int(o'401')
    integer(c_int), parameter :: KEY_DOWN      = int(o'402')
    integer(c_int), parameter :: KEY_UP        = int(o'403')
    integer(c_int), parameter :: KEY_LEFT      = int(o'404')
    integer(c_int), parameter :: KEY_RIGHT     = int(o'405')
    integer(c_int), parameter :: KEY_HOME      = int(o'406')
    integer(c_int), parameter :: KEY_BACKSPACE = int(o'407')
    integer(c_int), parameter :: KEY_F0        = int(o'410')

    integer(c_int), parameter :: KEY_F(1:12) = [ &
        int(o'411'), &
        int(o'412'), &
        int(o'413'), &
        int(o'414'), &
        int(o'415'), &
        int(o'416'), &
        int(o'417'), &
        int(o'420'), &
        int(o'421'), &
        int(o'422'), &
        int(o'423'), &
        int(o'424')  &
    ]

    integer(c_int), parameter :: KEY_DL        = int(o'510')
    integer(c_int), parameter :: KEY_IL        = int(o'511')
    integer(c_int), parameter :: KEY_DC        = int(o'512')
    integer(c_int), parameter :: KEY_IC        = int(o'513')
    integer(c_int), parameter :: KEY_EIC       = int(o'514')
    integer(c_int), parameter :: KEY_CLEAR     = int(o'515')
    integer(c_int), parameter :: KEY_EOS       = int(o'516')
    integer(c_int), parameter :: KEY_EOL       = int(o'517')
    integer(c_int), parameter :: KEY_SF        = int(o'520')
    integer(c_int), parameter :: KEY_SR        = int(o'521')
    integer(c_int), parameter :: KEY_NPAGE     = int(o'522')
    integer(c_int), parameter :: KEY_PPAGE     = int(o'523')
    integer(c_int), parameter :: KEY_STAB      = int(o'524')
    integer(c_int), parameter :: KEY_CTAB      = int(o'525')
    integer(c_int), parameter :: KEY_CATAB     = int(o'526')
    integer(c_int), parameter :: KEY_ENTER     = int(o'527')
    integer(c_int), parameter :: KEY_SRESET    = int(o'530')
    integer(c_int), parameter :: KEY_RESET     = int(o'531')
    integer(c_int), parameter :: KEY_PRINT     = int(o'532')
    integer(c_int), parameter :: KEY_LL        = int(o'533')
    integer(c_int), parameter :: KEY_A1        = int(o'534')
    integer(c_int), parameter :: KEY_A3        = int(o'535')
    integer(c_int), parameter :: KEY_B2        = int(o'536')
    integer(c_int), parameter :: KEY_C1        = int(o'537')
    integer(c_int), parameter :: KEY_C3        = int(o'540')
    integer(c_int), parameter :: KEY_BTAB      = int(o'541')
    integer(c_int), parameter :: KEY_BEG       = int(o'542')
    integer(c_int), parameter :: KEY_CANCEL    = int(o'543')
    integer(c_int), parameter :: KEY_CLOSE     = int(o'544')
    integer(c_int), parameter :: KEY_COMMAND   = int(o'545')
    integer(c_int), parameter :: KEY_COPY      = int(o'546')
    integer(c_int), parameter :: KEY_CREATE    = int(o'547')
    integer(c_int), parameter :: KEY_END       = int(o'550')
    integer(c_int), parameter :: KEY_EXIT      = int(o'551')
    integer(c_int), parameter :: KEY_FIND      = int(o'552')
    integer(c_int), parameter :: KEY_HELP      = int(o'553')
    integer(c_int), parameter :: KEY_MARK      = int(o'554')
    integer(c_int), parameter :: KEY_MESSAGE   = int(o'555')
    integer(c_int), parameter :: KEY_MOVE      = int(o'556')
    integer(c_int), parameter :: KEY_NEXT      = int(o'557')
    integer(c_int), parameter :: KEY_OPEN      = int(o'560')
    integer(c_int), parameter :: KEY_OPTIONS   = int(o'561')
    integer(c_int), parameter :: KEY_PREVIOUS  = int(o'562')
    integer(c_int), parameter :: KEY_REDO      = int(o'563')
    integer(c_int), parameter :: KEY_REFERENCE = int(o'564')
    integer(c_int), parameter :: KEY_REFRESH   = int(o'565')
    integer(c_int), parameter :: KEY_REPLACE   = int(o'566')
    integer(c_int), parameter :: KEY_RESTART   = int(o'567')
    integer(c_int), parameter :: KEY_RESUME    = int(o'570')
    integer(c_int), parameter :: KEY_SAVE      = int(o'571')
    integer(c_int), parameter :: KEY_SBEG      = int(o'572')
    integer(c_int), parameter :: KEY_SCANCEL   = int(o'573')
    integer(c_int), parameter :: KEY_SCOMMAND  = int(o'574')
    integer(c_int), parameter :: KEY_SCOPY     = int(o'575')
    integer(c_int), parameter :: KEY_SCREATE   = int(o'576')
    integer(c_int), parameter :: KEY_SDC       = int(o'577')
    integer(c_int), parameter :: KEY_SDL       = int(o'600')
    integer(c_int), parameter :: KEY_SELECT    = int(o'601')
    integer(c_int), parameter :: KEY_SEND      = int(o'602')
    integer(c_int), parameter :: KEY_SEOL      = int(o'603')
    integer(c_int), parameter :: KEY_SEXIT     = int(o'604')
    integer(c_int), parameter :: KEY_SFIND     = int(o'605')
    integer(c_int), parameter :: KEY_SHELP     = int(o'606')
    integer(c_int), parameter :: KEY_SHOME     = int(o'607')
    integer(c_int), parameter :: KEY_SIC       = int(o'610')
    integer(c_int), parameter :: KEY_SLEFT     = int(o'611')
    integer(c_int), parameter :: KEY_SMESSAGE  = int(o'612')
    integer(c_int), parameter :: KEY_SMOVE     = int(o'613')
    integer(c_int), parameter :: KEY_SNEXT     = int(o'614')
    integer(c_int), parameter :: KEY_SOPTIONS  = int(o'615')
    integer(c_int), parameter :: KEY_SPREVIOUS = int(o'616')
    integer(c_int), parameter :: KEY_SPRINT    = int(o'617')
    integer(c_int), parameter :: KEY_SREDO     = int(o'620')
    integer(c_int), parameter :: KEY_SREPLACE  = int(o'621')
    integer(c_int), parameter :: KEY_SRIGHT    = int(o'622')
    integer(c_int), parameter :: KEY_SRSUME    = int(o'623')
    integer(c_int), parameter :: KEY_SSAVE     = int(o'624')
    integer(c_int), parameter :: KEY_SSUSPEND  = int(o'625')
    integer(c_int), parameter :: KEY_SUNDO     = int(o'626')
    integer(c_int), parameter :: KEY_SUSPEND   = int(o'627')
    integer(c_int), parameter :: KEY_UNDO      = int(o'630')
    integer(c_int), parameter :: KEY_MOUSE     = int(o'631')
    integer(c_int), parameter :: KEY_RESIZE    = int(o'632')
    integer(c_int), parameter :: KEY_MAX       = int(o'777')

    integer(c_int), parameter :: ALL_MOUSE_EVENTS       = int(z'fffffff', c_int)
    integer(c_int), parameter :: BUTTON1_RELEASED       = int(z'0000001', c_int)
    integer(c_int), parameter :: BUTTON1_PRESSED        = int(z'0000002', c_int)
    integer(c_int), parameter :: BUTTON1_CLICKED        = int(z'0000004', c_int)
    integer(c_int), parameter :: BUTTON1_DOUBLE_CLICKED = int(z'0000008', c_int)
    integer(c_int), parameter :: BUTTON1_TRIPLE_CLICKED = int(z'0000010', c_int)
    integer(c_int), parameter :: BUTTON2_RELEASED       = int(z'0000020', c_int)
    integer(c_int), parameter :: BUTTON2_PRESSED        = int(z'0000040', c_int)
    integer(c_int), parameter :: BUTTON2_CLICKED        = int(z'0000080', c_int)
    integer(c_int), parameter :: BUTTON2_DOUBLE_CLICKED = int(z'0000100', c_int)
    integer(c_int), parameter :: BUTTON2_TRIPLE_CLICKED = int(z'0000200', c_int)
    integer(c_int), parameter :: BUTTON3_RELEASED       = int(z'0000400', c_int)
    integer(c_int), parameter :: BUTTON3_PRESSED        = int(z'0000800', c_int)
    integer(c_int), parameter :: BUTTON3_CLICKED        = int(z'0001000', c_int)
    integer(c_int), parameter :: BUTTON3_DOUBLE_CLICKED = int(z'0002000', c_int)
    integer(c_int), parameter :: BUTTON3_TRIPLE_CLICKED = int(z'0004000', c_int)
    integer(c_int), parameter :: BUTTON4_RELEASED       = int(z'0008000', c_int)
    integer(c_int), parameter :: BUTTON4_PRESSED        = int(z'0010000', c_int)
    integer(c_int), parameter :: BUTTON4_CLICKED        = int(z'0020000', c_int)
    integer(c_int), parameter :: BUTTON4_DOUBLE_CLICKED = int(z'0040000', c_int)
    integer(c_int), parameter :: BUTTON4_TRIPLE_CLICKED = int(z'0080000', c_int)
end module ncurses_const